Re-engineer Domain and Resource tests in response to #220
jhipster/generator-jhipster-quarkus pull request #234
Opened 2021-11-03 09:41 UTC by GeraldScott

This pull request is to resolve Issue #220 

The entity resource tests were failing because they were using the size of the array returned by the .get("/api/<%= entityApiUrl %>") clause as a proxy for the size of the dataset in the database.

There are a number of other problems with the REST tests:
- they are very slow because they are being used to test for required fields
- they are effectively Integration tests, not Unit tests because they use APIs to set up data and to test for database activity
- they are testing JPA functionality instead of leaving that to Hibernate and Liquibase

This Pull Request does the following:
- the REST tests have been stripped down to test for basic Create/Read/Update/Delete 
- database size before and after updates is checked using built-in Panache functionality, not an API call (which was causing the problem in the first place)
- the Domain tests have been enhanced to check for JPA annotations to test for "required" fields (instead of doing an API call as is curently the case) 
- there are two new test helper classes that implement the reflection to test for the JPA annotations
- add another domain test to check for "unique" fields

The advantages are:
- Issue 230 is resolved
- REST tests are much faster because they only use the API calls that are under test
- the domain tests of JPA annotations are more useful
- the test helper classes can be extended to test for any JPA annotation (@Min, @Max, etc), including the value of the annotation ("max = 256" for example)

2021-11-03 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/generator-jhipster-quarkus?pullRequest=234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/generator-jhipster-quarkus?pullRequest=234) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: GeraldScott<br/>:x: Gerald O'Sullivan<br/><hr/>**Gerald O'Sullivan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/generator-jhipster-quarkus?pullRequest=234) it.</sub>

2021-11-03 22:18 UTC, danielpetisme requested changes
Hi @GeraldScott, first of all, THANK YOU! Thanks for contributing and for your amazing work done!
I had couple of comments. The 2 main concerns are:
- the validation tests (in the create Entity and the fields required testing)
- the technical tests on the annotation presence, I never saw that before, could you please detail the objective.

Looking forward to merging your work soon!

2021-11-03 22:18 UTC, danielpetisme commented on generators/entity-server/templates/quarkus/src/test/java/package/_partials/create.ejs
>      public void create<%= entityClass %>() {
Please keep the validation tests (API should failed when creating with an existing ID)

2021-11-03 22:18 UTC, danielpetisme commented on generators/entity-server/templates/quarkus/src/test/java/package/_partials/create_with_field_required.ejs
> -<%_ for (let idx = 0; idx < fields.length; idx++) {
Please keep the validation tests (fields required)

2021-11-03 22:18 UTC, danielpetisme commented on generators/entity-server/templates/quarkus/src/test/java/package/_partials/get_all.ejs
> +        assertThat(Integer.parseInt(
try to keep assertation as "fluent" as possible (ie. assertation should look like be a plain English sentence).
Could you please extract the RESTAssured call into a local variable?

2021-11-03 22:18 UTC, danielpetisme commented on generators/entity-server/templates/quarkus/src/test/java/package/domain/EntityTest.java.ejs
> +    public void entityAnnotations() throws Exception {
What's the purpose of this test?
Sounds like a test `ArchTest.java`
I think this kind of "technical testing" should be done in a dedicated class. 
EntityTest should be dedicated to validate common entities behaviors, not their definition.

2021-11-03 22:18 UTC, danielpetisme commented on generators/entity-server/templates/quarkus/src/test/java/package/web/rest/EntityResourceTest.java.ejs
> -<%- include('../../_partials/create_with_field_required', this); -%>
Please re-include these tests

2021-11-03 22:18 UTC, danielpetisme commented on generators/server/templates/quarkus/src/test/java/package/ArchTest.java.ejs
> +            .importPackages("<%=packageName%>");
Very nice catch :)

2021-11-03 22:18 UTC, danielpetisme commented on generators/server/templates/quarkus/src/test/java/package/AssertAnnotations.java.ejs
> +public class AssertAnnotations {
I'm not very familiar with this kind of test.
Could you please elaborate your intent here

2022-10-21 17:55 UTC, mraible commented
@GeraldScott Can you please rebase this PR to fix conflicts?

2023-02-15 09:35 UTC, closed without merging

2023-02-15 09:38 UTC, GeraldScott commented
Hi Colleagues

I would like to close this pull request. My attempts to rebase have been unsuccessful because too many dependency conflicts have emerged in the passage of time.