85 Add support for skipClient option when generating a JHipster app
jhipster/generator-jhipster-quarkus pull request #87
Opened 2020-09-14 11:44 UTC by joewhite101

2020-09-14 11:48 UTC, joewhite101 commented
Fixes https://github.com/jhipster/jhipster-quarkus/issues/85

2020-09-14 14:28 UTC, nshaw approved these changes
Looks good to me. I was able to run mvnw successfully.

2020-09-15 11:43 UTC, avdev4j requested changes

2020-09-15 11:43 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +
Remove empty line

2020-09-15 11:43 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +                                        <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
Remove empty line

2020-09-15 11:43 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +
Remove empty line

2020-09-15 11:43 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +
Remove empty line

2020-09-15 11:43 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +            <profile>
It seems that the indentation is not the right one. It should be 4 spaces left below `<profiles>`.

2020-09-15 11:43 UTC, avdev4j commented on generators/server/files.js
> +
Remove empty line

2020-09-15 11:43 UTC, avdev4j commented on generators/server/files.js
> +                    file: 'package/web/rest/SpaFilter.java',
We should add a test case to ensure that the file is not generate when we choose no client framework.

2020-09-21 15:06 UTC, joewhite101 commented
Not ready to merge!

@avdev4j  Updated formatting based on notes.

Having an issue with the unit test. For some reason I can't get `skipClient` to pass through to the generator as "false". It is always set to true in the tests. Works correctly when running manually.  Tried using the app generator as the base test but the same issue.

2020-09-21 15:08 UTC, joewhite101 commented
And my local results are the opposite of git ...

2020-09-21 15:39 UTC, avdev4j commented
> Having an issue with the unit test. For some reason I can't get `skipClient` to pass through to the generator as "false". It is always set to true in the tests. Works correctly when running manually. Tried using the app generator as the base test but the same issue.

Wait! You remind me something, I think I already met this problem. The skipClient flag is ignore when we test it through blueprint tests. I don't why. Maybe we should open a ticket on the main repo. It's tricky but we need to fix that.

2020-09-21 15:47 UTC, joewhite101 commented
> > Having an issue with the unit test. For some reason I can't get `skipClient` to pass through to the generator as "false". It is always set to true in the tests. Works correctly when running manually. Tried using the app generator as the base test but the same issue.
> 
> Wait! You remind me something, I think I already met this problem. The skipClient flag is ignore when we test it through blueprint tests. I don't why. Maybe we should open a ticket on the main repo. It's tricky but we need to fix that.

You probably know more than I do. Do you want to open that ticket or should I?

2020-09-21 15:49 UTC, avdev4j commented
I can, If you want. I did not do it in the past (my bad) I can fix that ;)

2020-09-21 15:58 UTC, joewhite101 commented
@avdev4j Sounds good. Let me know the number. I think that one will need a bug bounty. That will be an issue for my other blueprint as well

2020-12-01 15:55 UTC, avdev4j commented
@joewhite101 I know why the skip-client doesn't work when testing server subgen (and blueprint).

This option is init by the app subgen and not by the server. If we want to test that, we need to switch the test from server to app and pass the right flag value.

I'll do a commit to fix that.

2020-12-02 13:29 UTC, avdev4j commented
the bug has been posted
https://github.com/jhipster/generator-jhipster/issues/13180

2020-12-02 13:36 UTC, avdev4j commented
I have intentionally remove the test related to the SpaFilter because we can't test it properly for the moment. let's merge this one and wait for a fix to test this specific scenario.

2020-12-02 13:36 UTC, avdev4j approved these changes

2020-12-02 13:39 UTC, merged