Oauth support
jhipster/generator-jhipster-quarkus pull request #90
Opened 2020-09-14 14:52 UTC by joewhite101

2020-09-14 14:54 UTC, mraible commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +    # Oauth2 and OIDC
```suggestion
    # OAuth 2.0 and OIDC
```

2020-09-15 12:04 UTC, avdev4j requested changes

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +            <dependency>
fix indentation

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +
remove empty line

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/pom.xml.ejs
> +
remove empty line

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +    # Oauth2 and OIDC
Indentation is not correct for all the properties added ;)

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +<%_ if (authenticationType !== 'oauth2') { _%>
maybe we can have else statement here instead of a new "if"

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +
remove empty line

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +
remove empty line

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +
remove empty line

2020-09-15 12:04 UTC, avdev4j commented on generators/server/templates/quarkus/src/main/resources/application.properties.ejs
> +
remove empty line

2020-11-24 20:31 UTC, danielpetisme commented
@joewhite101 @mraible Would you mind if I take over the Oauth2 support?
I would like to finish this feature for 1.0.0 milestone

2020-11-24 20:34 UTC, mraible commented
I don't mind at all. Please let me know if you need help testing it!

2020-11-25 09:32 UTC, joewhite101 commented
Hey @danielpetisme that would be awesome, thanks! All yours.

I've had this on my list for ages but never can get back to it. If I can help test or provide reviews let me know.

2020-11-25 09:54 UTC, avdev4j commented
I'm a bit confuse about this PR and this one https://github.com/jhipster/generator-jhipster-quarkus/pull/89. Maybe we should merge all in only one PR?

2020-11-28 15:06 UTC, danielpetisme commented
Closing PR for #124

2020-11-28 15:06 UTC, closed without merging